
expname: fc_GNT
rootdir: ./
render_stride: 2
distributed: False

### TRAINING
N_rand: 512   # 每次训练的渲染光束
num_source_views: 8
lrate_feature: 0.001
lrate_gnt: 0.0005
lrate_decay_factor: 0.5
lrate_decay_steps: 50000
single_net: True
trans_depth: 8

### TESTING
chunk_size: 2048

### RENDERING
N_importance: 64
N_samples: 64  # 每条光束的采样点
inv_uniform: True
white_bkgd: False

### CONSOLE AND TENSORBOARD
total_step: 600000
i_print: 100
save_interval: 60000

# dataset
train_dataset: scannet

resolution_type: lr
type2sample_weights: {"scannet": 1}
train_database_types: [scannet]
aug_pixel_center_sample: true
train_ray_num: 512

num_classes: 20
ignore_label: 20

val_set_list: configs/scannetv2_val_split.txt

# semantic_color_map: [
#   [174, 199, 232],  # wall
#   [152, 223, 138],  # floor
#   [31, 119, 180],   # cabinet
#   [255, 187, 120],  # bed
#   [188, 189, 34],   # chair
#   [140, 86, 75],    # sofa
#   [255, 152, 150],  # table
#   [214, 39, 40],    # door
#   [197, 176, 213],  # window
#   [148, 103, 189],  # bookshelf
#   [196, 156, 148],  # picture
#   [23, 190, 207],   # counter
#   [247, 182, 210],  # desk
#   [219, 219, 141],  # curtain
#   [255, 127, 14],   # refrigerator
#   [91, 163, 138],   # shower curtain
#   [44, 160, 44],    # toilet
#   [112, 128, 144],  # sink
#   [227, 119, 194],  # bathtub
#   [82, 84, 163],    # otherfurn
#   [248, 166, 116]  # invalid
# ]